### ISSUE TITLE
The manipulate bar window is opened at a weird position

### ISSUE THREAD

**Issue by luadam4c** [sg-s/puppeteer#11]
### What you were trying to do (include code to reproduce error)
```
x.manipulate
```

### What you expected to happen
The top of the manipulate window should be visible

### What actually happened
![image](https://user-images.githubusercontent.com/36715881/50261680-9f7cfb00-03db-11e9-8280-10bcae966e82.png)

This is a minor issue, but I always have to drag the window down after running x.manipulate

**Comment by luadam4c** [comment]
> @luadam4c how big is your screen? please run:
> 
> ```
> get(0,'ScreenSize')
> ```
> i think the way to fix it is in puppeteer -- to read out the screensize, and make sure it spawns in a place where the top if visible.

**1920 x 1020**, which is fairly standard.

> >> get(0, 'screensize')
> 
> ans =
> 
>            1           1        1920        1020

What about the fact that the sliders disappear when you change the height. For instance if you do:
```
manip.Position(4) = 100
```

It will display a warning:

> Warning: 'slider' control requires that 'Min' be less than 'Max'
> Control will not be rendered until all of its parameter values are valid

**Comment by sg-s** [comment]
should work -- tried it on a screen that is 1600 x 900 and everything seemed OK now
